### ISSUE TITLE
Doesn’t work on weekends

### ISSUE THREAD

**Issue by whoknows321** [Ameobea/robintrack#49]
When trying to view individual stock activity or popularity changes on the weekend, the robintrack service doesn’t work. It should be changed to let you be able to view the last available saved data(from Friday) rather than not work at all. Maybe it could also put up a alert/notification that “this data is not reflective of any activity today” or something. Because sometimes it’s useful to be able to use robintrack over the weekend

**Comment by Ameobea** [comment]
Hey!  Thanks for opening this issue.

The reason that the site wasn't available was because the server running my database + websites ran out of memory, causing the database service to crash.  People have been scraping the data on my website, despite me creating daily dumps of popularity history for all symbols, causing my cache to fill up and exhaust the memory for the database.

I've acquired a larger VPS with more RAM and vCPUs and will be migrating Robintrack there shortly.  Until then, I've re-started the database and will be trying to block the bots scraping the site.

Thanks again for reporting this, and for using Robintrack!
