### ISSUE TITLE
Download price data

### ISSUE THREAD

**Issue by Akababa** [Ameobea/robintrack#51]
Would it be at all possible to make the scraped price data downloadable? Despite my best efforts, I can't find free price data to join with the popularities - every API I tried so far only has some variant of daily historical data, or realtime quotes. It would be a great help to have hourly data going back a year or more (the best RH API can do is `interval=hour&span=month`)

**Comment by Ameobea** [comment]
Hey @Akababa thanks for opening this issue.  The way that Robintrack pulls its data from the Robinhood API uses multiple different worker processes to retrieve price and popularity data separately.  As a result, the price and popularity data points aren't actually matched exactly; they'll be within a few minutes of each other though assuming one of the processes didn't fail.

Since the quotes that I pull require me to login with my personal Robinhood account as opposed to the popularity data which can be pulled from a public API without any authentication, I decided to keep it out of the bulk data export.  The goal was to do everything I can to avoid any kind of legal issue with Robintrack.

That being said, you can pull the quote data used in the charts symbol by symbol from this endpoint: [https://robintrack.net/api/stocks/AAPL/quote_history](https://robintrack.net/api/stocks/AAPL/quote_history); just replace the symbol with that of the one you want to retrieve data for.  That will return all stored quotes for the given symbol in JSON format.

----

Anyway, I will not be adding price data to the downloadable data export.  However, feel free to make use of that JSON API I linked above (within reason - please don't hammer my servers with 100s of requests/minute).
