### ISSUE TITLE
What is the purpose of the ssh_tunnel in Justfile

### ISSUE THREAD

**Issue by averydev** [Ameobea/robintrack#84]
Hi there!

I'm curious what the purpose of these lines in the Justfile are?

```
ssh_tunnel:
  ssh -L 27017:ameo.design:27017 -L 6379:ameo.design:6379 root@ameo.design
```

**Comment by Ameobea** [comment]
I use it for local dev, to allow me to connect to the MongoDB and Redis running on my server as if they were running on `localhost`.  It's nice so that I don't have to set up special firewall rules to expose them to my IP address if I'm working remotely etc. and it gives me access to the live prod database so I can compare results to the live site as I work.

**Comment by averydev** [comment]
Cool! Thanks for explaining!
